language: node_js
node_js:
  - '8'
cache: npm

script:
  - set -e
  - npm run test
  - npm run build

deploy:
  skip_cleanup: true
  provider: npm
  email: demon@danwi.me
  api_key:
    secure: zMQhdZe3NQOZSq1ie5rrjyRanA/9jZuTIp3dBcs6Agqm8Wm6j1j3AuulUcQzA0LGmSm00pnO5nZwzZh/wmEfXgE/0OFZXiugN5f1qcN215f3VzZz8JhU2CSBFEl09bosPkZixR/N6TusDzFlmkfTmJlyUe6LTGywDMRoMr+r85DIKlVam2cc6tg9zp2Dq6JIu3yujrKvLZPwtDg9D7yQxt8Z7qyhaLmd6+0hZSS9LvTEvVvfJNGS82en0tPS34nN5hb51RHQHUEAyfNQmm+VMcf7Bol+poO+YSaXoE4HcDHh+CnlDIkCA7twd54RZ+tCQOhDfCk2xdgWJWFulXQ1hE1Grt05CavNHfMfrhCHBniD460Oofu+HZ9r6BRbpTOgMP5l5OdXG76cupQzpnkxfNxyaD8oV3KCIXHPJLJP2rv3r0v1qQr797NZ4L9IG3pUT3bnF7e1LNoClNk6ialKBQnYqWoymFfDklHAW8tvoDYFaWMH/6KKAepwYUjl46S95wz1qZfI2R2MLG+drIcYyk6AzwwU8pPvF0EBCmDOUWmuFTQwMrvPnBgblHNeMEFYavYA16gs5RdaP31XsCfUwK4k2i+eb6FlGwd1k8rYlQV3jKfoylugf8r7xPNUTxlHR54t3aLq9HA3kcsSyIPyBKB5HLqe47NO5+BEY0khaQY=
  on:
    tags: true
    repo: danwime/conctx
